#!/usr/bin/env bash
# Update package list and install Nginx
#!/bin/bash

# Add the Nginx stable repository
sudo add-apt-repository ppa:nginx/stable

# Update the software packages list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Change folder permissions
sudo chmod -R 755 /var/www

# Create an index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom 404.html page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure the default Nginx server block
sudo tee /etc/nginx/sites-enabled/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    if (\$request_filename ~ redirect_me){
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
EOL

# Restart Nginx without using systemctl
sudo service nginx restart

# Ensure Nginx starts on boot
sudo systemctl enable nginx

echo "Nginx is installed and configured."

